import {World,W,H,nearest} from './world';
export function renderer(canvas:HTMLCanvasElement){const ctx=canvas.getContext('2d')!;const atlas=new Image(),floor=new Image();atlas.src='/action-atlas.png';floor.src='/action-arena.png';let cw=0,ch=0;
const sprite=(n:number,x:number,y:number,size:number,flip=false)=>{if(!atlas.complete||!atlas.naturalWidth)return;const cell=atlas.width/4;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(atlas,(n%4)*cell,Math.floor(n/4)*cell,cell,cell,-size/2,-size*.7,size,size);ctx.restore();};
const text=(s:string,x:number,y:number,color='#e5f6ff',size=15)=>{ctx.font=`600 ${size}px system-ui`;ctx.textAlign='center';ctx.lineWidth=5;ctx.strokeStyle='#091421';ctx.strokeText(s,x,y);ctx.fillStyle=color;ctx.fillText(s,x,y);};
return (w:World,moving=false)=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(cw!==rect.width||ch!==rect.height){cw=rect.width;ch=rect.height;canvas.width=cw*dpr;canvas.height=ch*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#081520';ctx.fillRect(0,0,cw,ch);const zoom=cw<600?.7:Math.min(1.05,cw/1200);const vw=cw/zoom,vh=ch/zoom;const camX=Math.max(0,Math.min(W-vw,w.player.x-vw/2)),camY=Math.max(0,Math.min(H-vh,w.player.y-vh/2));ctx.save();ctx.scale(zoom,zoom);ctx.translate(-camX,-camY);ctx.imageSmoothingEnabled=false;if(floor.complete&&floor.naturalWidth)ctx.drawImage(floor,0,0,W,H);ctx.fillStyle='#04122035';ctx.fillRect(0,0,W,H);
for(const b of w.walls){ctx.fillStyle='#071924';ctx.fillRect(b.x,b.y+12,b.w,b.h);ctx.fillStyle='#274b60';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#57bed0';ctx.fillRect(b.x,b.y,b.w,4);}
// Connections and records are functional diagrams layered over the playable arena.
const line=(x1:number,y1:number,x2:number,y2:number,on:boolean)=>{ctx.strokeStyle=on?'#7df2ce':'#456274';ctx.lineWidth=on?4:2;ctx.setLineDash(on?[]:[9,9]);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);};
if(w.stage===0){line(1240,220,340,780,!!w.objects.find(o=>o.id==='clientA')?.done);line(1240,220,1190,770,!!w.objects.find(o=>o.id==='clientB')?.done);}
if(w.stage===1){line(700,440,1210,220,w.flags.api&&w.flags.sql);text('CLIENTE → APLICAÇÃO → SGBD',780,95,'#ffd9a0',17);}
if(w.stage===2){text('CURSOS EXISTENTES: 7',1100,100,'#ffdd9b',19);text('CADASTRADOS: '+(w.flags.accepted.join(', ')||'nenhum'),1210,355,'#a6ffe2',15);text('ISOLADOS: '+w.flags.rejected+' / 4',1210,860,'#ffcca5',15);}
if(w.stage===3){line(910,250,1090,480,!!w.objects.find(o=>o.id==='personPad')?.done);line(1260,250,1090,480,!!w.objects.find(o=>o.id==='projectPad')?.done);line(910,250,860,790,!!w.objects.find(o=>o.id==='attributePad')?.done);text(w.flags.leftMany?'N':'1',956,368,'#ffdba0',25);text(w.flags.rightMany?'M':'1',1210,367,'#ffdba0',25);text('VÍNCULOS TRANSPORTADOS: '+w.flags.links+' / 3',490,600,'#e1edff',15);}
if(w.stage===4){text('CHAVE ORIGINAL: (pedido, produto)',590,100,'#ffdfae',19);const sets=[['productTable',['price']],['orderTable',['clientFK']],['itemTable',['quantity','pair']],['clientTable',['name','city']]] as const;for(const [id,cols] of sets){const o=w.objects.find(o=>o.id===id)!;text(cols.filter(c=>w.flags.routed.includes(c)).map(c=>({price:'preço',clientFK:'cliente_id (FK)',quantity:'quantidade',pair:'pedido + produto (PK/FKs)',name:'nome',city:'cidade'}[c])).join(' · '),o.x,o.y+87,'#a3f4d6',13);}}
if(w.stage===5){const f=w.flags;ctx.fillStyle='#071c2ee8';ctx.fillRect(955,575,440,190);text(f.exists?'ROBO · id INT PK · status VARCHAR NOT NULL':'TABELA INEXISTENTE',1175,600,'#b5d7e8',14);if(f.exists){text(f.rows.length+' linha(s) · '+(f.filter===null?'SEM WHERE':'WHERE id='+f.filter),1175,626,'#ffdf9d',15);for(let i=0;i<f.rows.length;i++){const r=f.rows[i];text('id '+r.id+'  |  '+r.status,1175,650+i*24,r.status==='invasor'?'#ff8d9e':r.status==='avariado'?'#ffd190':'#9ff1d6',15);}}}
if(w.stage===6){text('ENTREGAS: A25 + A25 · B60 · C sem entrega',765,95,'#ffdd9f',17);text('B: '+w.flags.source+'    C: '+w.flags.dest,720,650,'#a7f5dc',24);if(w.flags.reportRows)text(w.flags.reportRows,930,330,'#aeffdb',15);}
const near=nearest(w);for(const o of w.objects){const active=o.kind==='exit'?w.goals.every(Boolean):!o.done;ctx.globalAlpha=active?1:.42;const bob=o.kind==='item'?Math.sin(w.tick*.09+o.x)*4:0;ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(o.x,o.y+20,35,13,0,0,7);ctx.fill();if(active){ctx.strokeStyle=o===near?'#fce2a6':o.kind==='exit'?'#5cffbc':'#77ddea66';ctx.lineWidth=o===near?3:1;ctx.beginPath();ctx.ellipse(o.x,o.y+17,42,21,0,0,7);ctx.stroke();}sprite(o.sprite,o.x,o.y+bob,o.kind==='exit'?140:o.kind==='item'||o.kind==='role'||o.kind==='source'?73:108);if(w.stage===3&&o.need){ctx.strokeStyle=o.done?'#9dffda':'#ffd5a1';ctx.lineWidth=3;ctx.beginPath();if(o.id==='relationPad'){ctx.moveTo(o.x,o.y-44);ctx.lineTo(o.x+53,o.y);ctx.lineTo(o.x,o.y+34);ctx.lineTo(o.x-53,o.y);ctx.closePath();}else if(o.id==='attributePad'){ctx.ellipse(o.x,o.y,58,30,0,0,Math.PI*2);}else ctx.rect(o.x-58,o.y-40,116,77);ctx.stroke();}text(o.done?'✓ '+o.label:o.label,o.x,o.y+58,o.done?'#88f0bc':o.kind==='item'?'#a5f8e2':'#ecf5ff',14);
if(w.stage===6&&['joinPad','groupPad','havingPad'].includes(o.id)){const v=w.flags[o.id==='joinPad'?'join':o.id==='groupPad'?'aggregate':'having'];if(v)text(v.toUpperCase(),o.x,o.y-65,'#ffc994',14);}ctx.globalAlpha=1;}
for(const e of w.enemies){const boss=e.type===3;if(boss&&!w.flags.bossVulnerable){ctx.strokeStyle='#c58cff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,70+Math.sin(w.tick*.05)*5,0,7);ctx.stroke();}sprite(4+e.type,e.x,e.y+Math.sin(w.tick*.1+e.phase)*3,boss?175:90,e.x>w.player.x);ctx.fillStyle='#172238';ctx.fillRect(e.x-25,e.y-64,50,5);ctx.fillStyle=boss?'#ffb45f':'#ff658e';ctx.fillRect(e.x-25,e.y-64,50*e.hp/e.max,5);if(boss)text('FRAGMENTADOR',e.x,e.y-84,'#ffb471',16);}
const p=w.player;if(p.invul%8<5){ctx.fillStyle='#001c2877';ctx.beginPath();ctx.ellipse(p.x,p.y+21,28,12,0,0,7);ctx.fill();sprite(moving?Math.floor(w.tick/5)%4:0,p.x,p.y,96,p.faceX<0);}if(w.carry){sprite(w.carry.sprite,p.x,p.y-63,49);text(w.carry.label,p.x,p.y-92,'#ffda91',13);}if(w.role)text(w.role==='tech'?'TÉCNICO':w.role.toUpperCase(),p.x,p.y+53,'#ffd78b',12);
for(const s of w.shots){ctx.fillStyle=s.hostile?'#ff638c':'#9bffed';ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(s.x,s.y,s.hostile?6:5,0,7);ctx.fill();}ctx.shadowBlur=0;for(const a of w.particles){ctx.globalAlpha=Math.min(1,a.life*2);ctx.fillStyle=a.color;ctx.fillRect(a.x,a.y,5,5);}ctx.globalAlpha=1;
// Edge beacons point toward nearby mission objects outside the camera.
for(const o of w.objects.filter(o=>!o.done&&o.kind!=='exit')){if(o.x>camX+45&&o.x<camX+vw-45&&o.y>camY+45&&o.y<camY+vh-45)continue;const x=Math.max(camX+25,Math.min(camX+vw-25,o.x)),y=Math.max(camY+30,Math.min(camY+vh-35,o.y));ctx.fillStyle='#7ce9da';ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fill();}
ctx.restore(); // A true world minimap, useful on a small phone camera.
const mw=110,mh=mw*H/W,mx=cw-mw-12,my=12;ctx.fillStyle='#081827d9';ctx.fillRect(mx,my,mw,mh);ctx.strokeStyle='#548399';ctx.strokeRect(mx,my,mw,mh);for(const o of w.objects){ctx.fillStyle=o.done?'#467366':o.kind==='exit'?'#bd9bff':'#76dcc6';ctx.fillRect(mx+o.x/W*mw-2,my+o.y/H*mh-2,4,4);}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(mx+p.x/W*mw,my+p.y/H*mh,3,0,7);ctx.fill();};}
