export const STEP=1/30, W=1536,H=1024;
export const INPUT={up:1,down:2,left:4,right:8,attack:16,interact:32,dash:64,drop:128};
export const chapters=[
 {title:'O arquivo fragmentado',area:'01 / Arquivo de origem',topic:'Arquivos · SGBD · Esquema e instância',max:140,color:'#ffcf83',brief:'As cópias do estoque divergiram. Recupere a versão mais recente e reconecte os serviços ao cadastro central.',goals:['Recuperar a versão atual','Reconectar os dois serviços','Restaurar o esquema'],hint:'Compare as revisões dos registros: a maior é a atualização mais recente. A estrutura descreve as colunas; a instância contém os valores atuais.'},
 {title:'A rede sob pressão',area:'02 / Central de processamento',topic:'SGBD · Arquitetura em camadas · Independência física',max:140,color:'#6be4d1',brief:'Religue cliente, aplicação e banco. Dois invasores vão disputar a última vaga: instale o controle de concorrência e execute o teste. Depois restaure o índice sem mudar o esquema.',goals:['Religar as três camadas','Proteger a última vaga','Restaurar o índice físico'],hint:'A requisição sai do cliente para a aplicação; a consulta SQL segue ao SGBD. Uma reserva precisa ser confirmada antes de outra observar a vaga. Índices pertencem ao nível interno.'},
 {title:'As portas da integridade',area:'03 / Registro de habitantes',topic:'Relação · PK/FK · Domínio · Integridade referencial',max:140,color:'#9fbdff',brief:'O curso 7 já existe. Transporte seis registros para o cadastro ou para a área de correção. Cada matrícula identifica uma pessoa; idade deve estar entre 0 e 130.',goals:['Cadastrar as duas pessoas válidas','Isolar os quatro registros inválidos'],hint:'Matrícula não pode ser nula ou repetida. Curso 99 não existe. Duas pessoas podem pertencer ao curso 7: repetir uma FK não duplica a chave primária.'},
 {title:'A ponte de Chen',area:'04 / Praça dos projetos',topic:'Modelo E/R · Entidades · Atributos · Cardinalidade',max:140,color:'#53d8ff',brief:'Reconstrua o diagrama que sustenta a ponte. Lia participa de dois projetos; Ravi também participa do primeiro. Instale os ramificadores necessários e envie os três vínculos.',goals:['Montar o diagrama conceitual','Transportar os três vínculos'],hint:'O retângulo representa uma entidade; a elipse, seu atributo; o losango, a associação. Há várias pessoas por projeto e vários projetos por pessoa. Cada extremidade precisa permitir isso.'},
 {title:'O armazém das cópias',area:'05 / Oficina de normalização',topic:'1FN · 2FN · 3FN · Mapeamento 1:N e N:M',max:150,color:'#e2a0ff',brief:'A planilha do armazém guarda listas e repete dados a cada item. Desmonte-a no separador e leve cada atributo à tabela determinada por sua chave.',goals:['Separar os grupos de valores','Eliminar as dependências parciais','Reconstruir as relações sem redundância'],hint:'Preço depende do produto; quantidade, do par pedido+produto. Cliente pertence ao pedido; nome e cidade pertencem ao cliente. A tabela de itens liga pedidos a produtos.'},
 {title:'A forja SQL',area:'06 / Laboratório de estruturas',topic:'Modelo físico · DDL · INSERT · SELECT · UPDATE · DELETE',max:150,color:'#ffba7f',brief:'Equipe ferramentas SQL nos pedestais. Construa a tabela, insira os quatro robôs do backup, repare apenas o robô 3 e remova apenas o invasor 4. As ferramentas agem no console da forja.',goals:['Criar estrutura e inserir quatro linhas','Reparar somente o robô 3','Remover o invasor e manter a tabela'],hint:'CREATE constrói a estrutura. INSERT recupera uma linha do backup por uso. SELECT permite conferir o filtro. UPDATE e DELETE sem WHERE atingem todas as linhas; DROP também destrói a estrutura.'},
 {title:'O guardião do tudo ou nada',area:'07 / Núcleo de energia',topic:'JOIN · GROUP BY/HAVING · Transações · ACID',max:140,color:'#ff809e',brief:'Monte o relatório de todas as bases, inclusive as sem entregas, e descubra quem tem energia suficiente. Transfira 40 unidades de B para C. Haverá uma falha antes da primeira confirmação. Recupere a operação e derrube o guardião.',goals:['Produzir o relatório completo','Confirmar a transferência íntegra','Derrotar o Fragmentador'],hint:'LEFT JOIN mantém bases sem entregas. SUM por base agrega antes de HAVING. B tem 60 e C tem 0. Se o débito ocorrer sem crédito, ROLLBACK restaura ambos; COMMIT só após as duas alterações.'}
];
export type Obj={id:string,x:number,y:number,kind:'item'|'station'|'source'|'role'|'exit',label:string,detail:string,payload?:string,need?:string,sprite:number,color?:string,done?:boolean,value?:string};
export type Enemy={id:number,x:number,y:number,hp:number,max:number,type:number,cool:number,phase:number};
export type Shot={x:number,y:number,vx:number,vy:number,life:number,hostile:boolean};
export type Particle={x:number,y:number,vx:number,vy:number,life:number,color:string};
export type RecordPacket={x:number,y:number,value:number,speed:number,op:'INSERT'|'UPDATE'};
export type World={version:number,stage:number,seed:number,rng:number,tick:number,player:{x:number,y:number,hp:number,faceX:number,faceY:number,invul:number,attack:number,dash:number,dashTime:number},objects:Obj[],enemies:Enemy[],shots:Shot[],particles:Particle[],packets:RecordPacket[],walls:{x:number,y:number,w:number,h:number}[],goals:boolean[],carry:Obj|null,role:string,errors:number,deaths:number,kills:number,interactLock:boolean,dropLock:boolean,spawn:number,finished:boolean,flags:Record<string,any>,messages:{text:string,until:number,kind:string}[],events:number};
function rnd(w:World){w.rng=(Math.imul(w.rng,1664525)+1013904223)>>>0;return w.rng/4294967296;}
export function tell(w:World,text:string,kind='info'){w.messages.push({text,kind,until:w.tick+240});if(w.messages.length>4)w.messages.shift();w.events++;}
const item=(id:string,x:number,y:number,label:string,payload:string,sprite=10,detail='E · pegar'):Obj=>({id,x,y,kind:'item',label,payload,sprite,detail});
const station=(id:string,x:number,y:number,label:string,detail:string,sprite=9,need?:string):Obj=>({id,x,y,kind:'station',label,detail,sprite,need});
function enemy(w:World,x:number,y:number,type=0){const boss=type===3;w.enemies.push({id:w.tick+Math.floor(rnd(w)*9999),x,y,hp:boss?24:3,max:boss?24:3,type,cool:40+Math.floor(rnd(w)*80),phase:rnd(w)*6});}
export function createWorld(stage:number,seed:number):World{const w:World={version:3,stage,seed,rng:(seed+stage*9187+1)>>>0,tick:0,player:{x:170,y:510,hp:100,faceX:1,faceY:0,invul:0,attack:0,dash:0,dashTime:0},objects:[],enemies:[],shots:[],particles:[],packets:[],walls:[],goals:chapters[stage].goals.map(()=>false),carry:null,role:'',errors:0,deaths:0,kills:0,interactLock:false,dropLock:false,spawn:240,finished:false,flags:{},messages:[],events:0};
if(stage===0){w.flags={latest:false,linked:0};w.objects=[item('old',360,220,'LOTE L7 · 40 · REV 1','old'),item('current',720,780,'LOTE L7 · 30 · REV 3','current'),item('schema',620,210,'qtd INT · CHECK >= 0','schema'),station('core',1240,220,'CADASTRO CENTRAL','Último log confirmado: revisão 3.',8),station('clientA',340,780,'SERVIÇO A · 40','E · ligar ao cadastro central',9),station('clientB',1190,770,'SERVIÇO B · 35','E · ligar ao cadastro central',9),station('catalog',740,480,'CATÁLOGO','Restaurar a definição das colunas.',15)];w.walls=[{x:530,y:370,w:310,h:40}];}
if(stage===1){w.flags={api:false,sql:false,lock:false};w.objects=[item('request',310,220,'PEDIDO DO CLIENTE','request'),item('sql',310,790,'CONSULTA SQL','sql'),item('lock',720,790,'CONTROLE DE CONCORRÊNCIA','lock'),item('index',780,200,'ÍNDICE DE BUSCA','index'),station('api',700,440,'SERVIDOR DE APLICAÇÃO','Recebe o pedido do cliente e aplica regras.'),station('db',1210,220,'SGBD · CONSULTAS','Recebe SQL vindo da aplicação.',8),station('reservation',1240,720,'ÚLTIMA VAGA','Instale o controle; E sem carga testa duas reservas.',8),station('internal',1030,450,'NÍVEL INTERNO','Estrutura física de armazenamento e acesso.'),station('concept',360,500,'ESQUEMA CONCEITUAL','Tabelas e relações: não precisa mudar para criar índice.')];}
if(stage===2){const rows=[{id:11,course:7,age:20},{id:12,course:7,age:22},{id:11,course:7,age:25},{id:null,course:7,age:19},{id:13,course:99,age:21},{id:14,course:7,age:-2}];w.flags={accepted:[],rejected:0,processed:0};w.objects=[...rows.map((r,i)=>({...item('row'+i,320+(i%2)*360,200+Math.floor(i/2)*285,`ID ${r.id??'NULL'} · C${r.course} · ${r.age} anos`,'row'),value:JSON.stringify(r)})),station('register',1220,260,'CADASTRAR','PK matrícula · FK curso · idade 0..130',8),station('reject',1210,770,'CORRIGIR DEPOIS','Isolar registros que violam restrições.',15),station('course7',1050,510,'CURSO 7 · EXISTENTE','E · tentar remover curso referenciado',9)];}
if(stage===3){w.flags={parts:0,leftMany:false,rightMany:false,links:0};w.objects=[item('person',290,200,'PESQUISADOR','person',8),item('project',290,800,'PROJETO','project',8),item('relation',620,200,'PARTICIPA','relation'),item('attribute',630,790,'NOME','attribute'),{...item('fan',260,500,'RAMIFICADOR N','fan',12),kind:'source',detail:'E · retirar um ramificador'},station('personPad',910,250,'RETÂNGULO · PESSOAS','Lia e Ravi: objetos com existência própria.',8,'person'),station('projectPad',1260,250,'RETÂNGULO · PROJETOS','Farol e Horta: objetos com existência própria.',8,'project'),station('relationPad',1090,480,'LOSANGO · ASSOCIAÇÃO','Quem participa de qual projeto?',9,'relation'),station('attributePad',860,790,'ELIPSE · CARACTERÍSTICA','Como cada pesquisador é chamado?',9,'attribute'),station('leftFan',760,480,'PROJETOS POR PESSOA','Uma pessoa pode participar de mais de um projeto.'),station('rightFan',1240,760,'PESSOAS POR PROJETO','Um projeto pode receber mais de uma pessoa.'),station('bridge',480,500,'ATIVAR PONTE','Enviar Lia–Farol, Lia–Horta, Ravi–Farol.',14)];}
if(stage===4){w.flags={split:false,routed:[]};w.objects=[item('bundle',340,230,'PLANILHA COM LISTAS','bundle',12),station('splitter',620,500,'SEPARADOR DE LINHAS','Uma linha por par pedido + produto.',9),station('productTable',1190,190,'PRODUTO · PK produto','O que depende apenas do produto?',8),station('orderTable',1190,410,'PEDIDO · PK pedido','Cada pedido tem um cliente.',8),station('itemTable',1190,630,'ITEM · PK pedido + produto','Quantidade depende do par completo.',8),station('clientTable',760,820,'CLIENTE · PK cliente','Cadastro independente dos pedidos.',8)];w.walls=[{x:720,y:290,w:270,h:40}];}
if(stage===5){w.flags={exists:false,rows:[],filter:null,preview:null,inserted:0};const names=['CREATE','INSERT','UPDATE','DELETE','DROP'];w.objects=[...names.map((v,i)=>({...item('tool'+v,300+(i%2)*290,200+Math.floor(i/2)*280,v,v,11),kind:'role' as const,detail:'E · equipar ferramenta '+v})),station('forge',1170,480,'CONSOLE DA FORJA','E · executar a ferramenta equipada.',8),station('where3',900,220,'WHERE id = 3','Equipar filtro do robô avariado.'),station('where4',900,800,'WHERE id = 4','Equipar filtro do invasor.'),station('all',600,790,'SEM WHERE','Remover filtro: todas as linhas são atingidas.'),station('select',1190,220,'SELECT · CONFERIR','Exibir as linhas atingidas pelo filtro.',15)];}
if(stage===6){w.flags={join:'',aggregate:'',having:'',report:false,transaction:false,debited:false,credited:false,fault:false,failed:false,source:60,dest:0,bossVulnerable:false};w.objects=[{...item('left',280,170,'LEFT JOIN','left'),kind:'source'},{...item('inner',280,330,'INNER JOIN','inner'),kind:'source'},{...item('group',560,170,'GROUP BY base · SUM','group'),kind:'source'},{...item('having',560,330,'HAVING SUM >= 40','having'),kind:'source'},{...item('where',280,800,'WHERE energia >= 40','where'),kind:'source'},station('joinPad',900,180,'UNIR BASES E ENTREGAS','Bases A/B/C; entregas A25, A25, B60.'),station('groupPad',1190,180,'AGREGAR POR BASE','Calcular energia total de cada base.'),station('havingPad',1190,780,'FILTRAR GRUPOS','Liberar somente bases com total >=40.'),station('report',890,380,'EXECUTAR RELATÓRIO','Todas as bases devem aparecer, inclusive sem entrega.',15),station('begin',600,530,'BEGIN','Abrir transferência de 40 unidades.'),station('origin',340,600,'BASE B · 60','E · retirar 40 unidades dentro da transação.',8),station('destination',940,800,'BASE C · 0','E · creditar as 40 unidades.',8),station('rollback',620,790,'ROLLBACK','Desfazer toda a transferência.'),station('commit',1210,400,'COMMIT','Confirmar débito e crédito juntos.')];enemy(w,1270,580,3);}
w.objects.push({id:'exit',x:1410,y:500,kind:'exit',label:'PORTAL',detail:'Recupere o distrito para abrir.',sprite:14});
for(let i=0;i<4;i++)enemy(w,700+rnd(w)*550,180+rnd(w)*650,i%3);tell(w,chapters[stage].brief);return w;}
export function score(w:World){const max=chapters[w.stage].max;return Math.max(Math.round(max*.6),max-Math.min(40,w.errors*5)-Math.min(10,w.deaths*2));}
function dist(a:{x:number,y:number},b:{x:number,y:number}){return Math.hypot(a.x-b.x,a.y-b.y);}
export function nearest(w:World){return w.objects.filter(o=>!o.done&&dist(o,w.player)<100).sort((a,b)=>dist(a,w.player)-dist(b,w.player))[0];}
function burst(w:World,x:number,y:number,color:string,n=12){for(let i=0;i<n;i++){const a=i/n*Math.PI*2;w.particles.push({x,y,vx:Math.cos(a)*65,vy:Math.sin(a)*65,life:.6,color});}}
function fail(w:World,msg:string){w.errors++;tell(w,msg,'warn');burst(w,w.player.x,w.player.y,'#ffbd7b',8);}
function complete(w:World,index:number,msg:string){if(w.goals[index])return;w.goals[index]=true;w.player.hp=Math.min(100,w.player.hp+20);tell(w,msg,'success');burst(w,w.player.x,w.player.y,'#76ffd0',20);}
function drop(w:World){if(!w.carry)return;const o=w.carry;o.x=w.player.x-40;o.y=w.player.y+30;w.objects.push(o);w.carry=null;tell(w,'Carga no chão. Você pode recuperá-la.');}
function consume(w:World){w.carry=null;}
function resetTransfer(w:World){w.flags.transaction=false;w.flags.debited=false;w.flags.credited=false;w.flags.failed=false;w.flags.source=60;w.flags.dest=0;w.objects=w.objects.filter(o=>o.payload!=='energy');if(w.carry?.payload==='energy')w.carry=null;}
function interact(w:World){const o=nearest(w);if(!o){if(w.carry)drop(w);return;}if(o.kind==='exit'){if(w.goals.every(Boolean)){w.finished=true;tell(w,'Distrito recuperado. Registro de missão enviado.','success');}else tell(w,'O portal precisa de todos os sistemas recuperados.','warn');return;}
if(o.kind==='role'){w.role=o.payload!;tell(w,`Ferramenta equipada: ${o.label}. ${o.detail}`);burst(w,o.x,o.y,'#ffdf83');return;}
if(o.kind==='item'||o.kind==='source'){if(w.carry)drop(w);w.carry={...o,kind:'item'};if(o.kind==='item')w.objects=w.objects.filter(x=>x.id!==o.id);tell(w,`Transportando ${o.label}. E para entregar; Q para soltar.`);return;}
const cargo=w.carry?.payload;
if(w.stage===0){const f=w.flags;if(o.id==='core'){if(cargo==='current'){consume(w);o.done=true;f.latest=true;complete(w,0,'Revisão 3 recuperada: estoque 30. As cópias antigas estavam inconsistentes.');}else if(cargo)fail(w,'Esse registro não corresponde ao último log confirmado. Compare as revisões.');else tell(w,o.detail);}if(o.id==='clientA'||o.id==='clientB'){if(!f.latest)fail(w,'A fonte central ainda não tem a versão atual. Recupere o cadastro primeiro.');else{o.done=true;o.label=o.id==='clientA'?'SERVIÇO A · 30':'SERVIÇO B · 30';f.linked++;tell(w,'O serviço consulta a mesma fonte: não mantém mais uma cópia isolada.','success');if(f.linked===2)complete(w,1,'Os dois serviços agora observam estoque 30. A atualização deixa de divergir entre arquivos.');}}if(o.id==='catalog'){if(cargo==='schema'){consume(w);o.done=true;complete(w,2,'Esquema restaurado: qtd é inteiro não negativo. Estoque 30 é um valor da instância; não define a estrutura.');}else if(cargo)fail(w,'O catálogo precisa da definição das colunas, não de um registro de estoque.');else tell(w,o.detail);}}
if(w.stage===1){const f=w.flags;if(o.id==='api'||o.id==='db'){const wanted=o.id==='api'?'request':'sql';if(cargo===wanted){consume(w);o.done=true;f[o.id==='api'?'api':'sql']=true;tell(w,o.id==='api'?'O cliente alcançou a aplicação. A regra de negócio está na camada intermediária.':'O SGBD processou o SQL e devolveu dados. Ele não é um compilador de Java.','success');if(f.api&&f.sql)complete(w,0,'Cliente → aplicação → SGBD. As três camadas estão conectadas.');}else if(cargo)fail(w,'Esse pacote não pertence a esta camada. A aplicação recebe o pedido; o SGBD recebe a consulta SQL.');else tell(w,o.detail);}if(o.id==='reservation'){if(cargo==='lock'){consume(w);f.lock=true;tell(w,'Controle de concorrência instalado. Use novamente, sem carga, para testar.');}else if(cargo)fail(w,'Este módulo não coordena as duas reservas simultâneas.');else if(f.lock){o.done=true;complete(w,1,'Teste concluído: a primeira reserva consumiu a vaga; a segunda encontrou zero. Nenhuma dupla reserva.');}else fail(w,'Os dois clientes leram vaga=1 e confirmaram. Sem controle, a última vaga foi vendida duas vezes.');}if(o.id==='internal'){if(cargo==='index'){consume(w);o.done=true;complete(w,2,'Índice físico restaurado. A mesma consulta continua funcionando sem alterar tabelas ou aplicações.');}else if(cargo)fail(w,'Esta melhoria física precisa do índice de busca.');else tell(w,o.detail);}if(o.id==='concept'){if(cargo==='index')fail(w,'Alterar o esquema lógico não é necessário para reconstruir este índice físico.');else tell(w,o.detail);}}
if(w.stage===2){const f=w.flags;if(o.id==='register'||o.id==='reject'){if(cargo!=='row'){tell(w,o.detail);return;}const r=JSON.parse(w.carry!.value!),why=r.id===null?'A PK está nula.':f.accepted.includes(r.id)?'A PK já está cadastrada.':r.course!==7?'A FK aponta para um curso inexistente.':r.age<0||r.age>130?'A idade viola o domínio.':'';const valid=!why;if(o.id==='register'&&valid){f.accepted.push(r.id);f.processed++;consume(w);tell(w,`Pessoa ${r.id} cadastrada. A FK curso=7 pode aparecer em várias pessoas.`,'success');}else if(o.id==='reject'&&!valid){f.rejected++;f.processed++;consume(w);tell(w,why+' Registro isolado para correção.','success');}else fail(w,valid?'O registro respeita as restrições. Isolá-lo impede um cadastro válido.':why+' A inserção foi bloqueada.');if(f.accepted.length===2)complete(w,0,'Duas pessoas distintas compartilham o curso 7. PK única; FK pode repetir.');if(f.rejected===4)complete(w,1,'Nulos na PK, repetição de chave, referência órfã e domínio inválido foram isolados.');}if(o.id==='course7'){if(f.accepted.length)fail(w,'DELETE bloqueado por RESTRICT: pessoas ainda referenciam o curso. A FK protege a integridade referencial.');else tell(w,'Este curso será necessário aos cadastros. Mantenha o registro pai.');}}
if(w.stage===3){const f=w.flags;if(o.need){if(cargo===o.need){consume(w);o.done=true;f.parts++;tell(w,'Componente do diagrama restaurado.','success');if(f.parts===4)complete(w,0,'Entidades, atributo e relacionamento conectados. O modelo ainda não depende de um SGBD.');}else if(cargo)fail(w,'O componente não representa esse papel no mini-mundo. Observe a forma e a função da estação.');else tell(w,o.detail);}if(o.id==='leftFan'||o.id==='rightFan'){if(cargo==='fan'){const key=o.id==='leftFan'?'leftMany':'rightMany';f[key]=true;consume(w);o.done=true;tell(w,o.id==='leftFan'?'Cada pessoa agora alcança vários projetos.':'Cada projeto agora recebe várias pessoas.','success');}else if(cargo)fail(w,'Esta extremidade precisa de um ramificador para admitir vários vínculos.');else tell(w,o.detail);}if(o.id==='bridge'){if(!w.goals[0]){tell(w,'O diagrama precisa dos quatro componentes antes de transportar vínculos.');return;}f.links=1;if(!f.leftMany){fail(w,'Lia–Farol passou; Lia–Horta foi bloqueado. A mesma pessoa precisa alcançar dois projetos.');return;}f.links=2;if(!f.rightMany){fail(w,'Ravi–Farol foi bloqueado: Farol já recebeu Lia. O projeto precisa receber mais de uma pessoa.');return;}f.links=3;o.done=true;complete(w,1,'Lia–Farol, Lia–Horta e Ravi–Farol atravessaram. A associação exige N:M.');}}
if(w.stage===4){const f=w.flags;if(o.id==='splitter'){if(cargo==='bundle'){consume(w);o.done=true;f.split=true;const values=[['price','preço · depende de produto'],['clientFK','cliente_id · depende de pedido'],['quantity','qtd · depende de pedido + produto'],['name','nome · depende de cliente'],['city','cidade · depende de cliente'],['pair','PK/FKs · pedido + produto']];values.forEach(([id,label],i)=>w.objects.push(item(id,300+(i%2)*290,180+Math.floor(i/2)*280,label,id)));complete(w,0,'As listas viraram linhas atômicas, uma por item. Agora elimine as repetições entre linhas.');}else if(cargo)fail(w,'O separador recebe a planilha com listas.');else tell(w,o.detail);}else if(o.id.endsWith('Table')){const target:Record<string,string>={price:'productTable',clientFK:'orderTable',quantity:'itemTable',name:'clientTable',city:'clientTable',pair:'itemTable'};if(!cargo){tell(w,o.detail);return;}if(target[cargo]===o.id){const part=cargo;f.routed.push(part);consume(w);tell(w,part==='price'?'Preço saiu da chave composta: depende apenas de produto.':part==='quantity'?'Quantidade pertence ao par completo pedido + produto.':part==='clientFK'?'FK cliente_id no lado N: cada pedido aponta para um cliente.':part==='pair'?'ITEM associa pedidos a produtos por duas FKs e uma PK composta.':`${part==='name'?'Nome':'Cidade'} agora pertence ao cliente, sem repetição por pedido.`,'success');if(['price','clientFK','quantity'].every(v=>f.routed.includes(v)))complete(w,1,'Dependências parciais separadas. O item guarda o que depende de sua chave inteira.');if(['name','city','pair'].every(v=>f.routed.includes(v)))complete(w,2,'Dependências transitivas removidas. Alterar a cidade exige atualizar um só cadastro de cliente.');}else fail(w,'Esse atributo não depende da chave desta tabela. A colocação manteria uma dependência indevida.');}}
if(w.stage===5){const f=w.flags;if(o.id==='where3'||o.id==='where4'||o.id==='all'){f.filter=o.id==='all'?null:o.id==='where3'?3:4;f.preview=null;tell(w,f.filter?`Filtro equipado: WHERE id = ${f.filter}. Confira no SELECT.`:'Filtro removido. UPDATE e DELETE atingirão todas as linhas.','info');return;}if(o.id==='select'){if(!f.exists){tell(w,'SELECT falhou: a tabela não existe. Construa a estrutura.');return;}const hits=f.rows.filter((r:any)=>f.filter===null||r.id===f.filter);f.preview=f.filter;tell(w,`SELECT: ${hits.length} linha(s) → ${hits.map((r:any)=>r.id+':'+r.status).join(', ')||'nenhuma'}.`);return;}if(o.id==='forge'){if(w.goals.every(Boolean)){tell(w,'Forja validada. Os três robôs estão ativos; entre no portal.');return;}const action=w.role;if(!action){tell(w,'Equipe uma ferramenta SQL em um pedestal.');return;}if(action==='CREATE'){if(f.exists)tell(w,'A tabela já existe. CREATE não insere os registros.');else{f.exists=true;f.rows=[];f.inserted=0;tell(w,'CREATE TABLE robo (id INT PRIMARY KEY, status VARCHAR(12) NOT NULL). Estrutura criada; zero linhas.','success');}}else if(!f.exists){fail(w,'A tabela não existe: construa sua estrutura antes de manipular linhas.');}else if(action==='INSERT'){const id=[1,2,3,4].find(n=>!f.rows.some((r:any)=>r.id===n));if(!id)tell(w,'As quatro linhas já existem. Inserir uma PK repetida seria rejeitado.');else{if(id===4)w.goals[2]=false;if(id===3)w.goals[1]=false;f.rows.push({id,status:id===3?'avariado':id===4?'invasor':'ativo'});f.inserted++;tell(w,`INSERT adicionou robô ${id}. Estrutura preservada; ${f.rows.length} linhas.`, 'success');if(f.rows.length===4)complete(w,0,'DDL criou a estrutura; quatro INSERTs construíram a instância.');}}else if(action==='UPDATE'){if(f.filter!==3){fail(w,'O UPDATE atingiu registros além do robô 3. A cópia de segurança restaurou seus estados; equipe WHERE id=3.');}else{const r=f.rows.find((r:any)=>r.id===3);if(!r)fail(w,'O robô 3 não existe na tabela. Restaure a linha com INSERT.');else{r.status='ativo';complete(w,1,'UPDATE ... WHERE id=3 reparou somente o robô avariado. As demais linhas foram preservadas.');}}}else if(action==='DELETE'){const before=f.rows.length;f.rows=f.rows.filter((r:any)=>f.filter!==null&&r.id!==f.filter);if(f.filter===4&&[1,2,3].every(n=>f.rows.some((r:any)=>r.id===n))){complete(w,2,'DELETE ... WHERE id=4 removeu o invasor. A tabela e os outros três robôs continuam existindo.');}else{fail(w,`DELETE removeu ${before-f.rows.length} linha(s). A estrutura continua existindo, mas a missão perdeu registros necessários.`);w.goals[0]=false;w.goals[1]=false;w.goals[2]=false;}}else if(action==='DROP'){f.exists=false;f.rows=[];w.goals.fill(false);f.exitAnnounced=false;fail(w,'DROP TABLE removeu linhas e estrutura. Reconstrua com CREATE e recupere as linhas com INSERT.');}}}
if(w.stage===6){const f=w.flags;if(['joinPad','groupPad','havingPad'].includes(o.id)){if(f.report){tell(w,'O relatório já foi validado. Siga para a transferência.');return;}const allowed=o.id==='joinPad'?['left','inner']:o.id==='groupPad'?['group']:['having','where'];if(!cargo){tell(w,o.detail);return;}if(!allowed.includes(cargo)){fail(w,'Esse operador pertence a outra etapa da consulta.');return;}f[o.id==='joinPad'?'join':o.id==='groupPad'?'aggregate':'having']=cargo;consume(w);tell(w,'Operador instalado. Use EXECUTAR RELATÓRIO para observar o resultado.');}
if(o.id==='report'){f.reportRows=f.join==='left'?(f.having==='where'?'B=60 (A e C omitidas)':'A=50 · B=60 · C=NULL'):'A=50 · B=60 (C omitida)';if(f.join!=='left'){fail(w,'INNER JOIN omitiu a base C, que não tem entrega. O relatório deve incluir todas as bases.');return;}if(f.aggregate!=='group'){fail(w,'Sem GROUP BY base, a energia não foi totalizada por destino.');return;}if(f.having!=='having'){fail(w,'WHERE descartou as duas entregas de 25 de A antes da soma. A tem 50 no total e deveria passar por HAVING total>=40.');return;}f.report=true;o.done=true;complete(w,0,'LEFT JOIN + SUM: A=50, B=60, C=NULL (sem entrega). GROUP BY + HAVING total>=40 libera A e B. Transfira 40 de B para C.');}
if(['begin','origin','destination','rollback','commit'].includes(o.id)){if(w.goals[1]){tell(w,'Transferência já confirmada: B=20, C=40. Os saldos permanecem duráveis.');return;}if(!f.report){tell(w,'Valide o relatório para liberar a transferência.');return;}if(o.id==='begin'){if(f.failed)tell(w,'Transação abortada. Use ROLLBACK.','warn');else{f.transaction=true;tell(w,'BEGIN: o débito e o crédito formam uma única unidade.');}}if(o.id==='origin'){if(!f.transaction||f.failed)fail(w,'Abra uma transação válida antes de debitar a base B.');else if(f.debited)tell(w,'As 40 unidades já estão em trânsito.');else{if(w.carry)drop(w);f.debited=true;f.source=20;w.carry=item('energy',0,0,'40 UNIDADES DE ENERGIA','energy');tell(w,'B=20; carga=40. O débito ainda não está confirmado.');}}if(o.id==='destination'){if(cargo!=='energy')tell(w,'A base C aguarda a carga de 40 unidades.');else if(!f.fault){f.fault=true;f.failed=true;tell(w,'FALHA NO CRÉDITO! B já foi debitada, mas C não recebeu. Recupere a transação inteira.','warn');}else if(f.failed)tell(w,'A transação abortou. Use ROLLBACK antes de tentar de novo.','warn');else{consume(w);f.credited=true;f.dest=40;tell(w,'B=20, C=40. Soma=60. As duas alterações aguardam COMMIT.');}}if(o.id==='rollback'){resetTransfer(w);tell(w,'ROLLBACK: B=60 e C=0. Todas as alterações desde BEGIN foram desfeitas.','success');}if(o.id==='commit'){if(f.transaction&&f.debited&&f.credited&&!f.failed){f.transaction=false;complete(w,1,'COMMIT: B=20, C=40. Tudo ou nada, total preservado. O escudo do Fragmentador caiu.');}else{fail(w,'Confirmação bloqueada: a transferência está incompleta. Os saldos foram restaurados.');resetTransfer(w);}}}f.bossVulnerable=w.goals[0]&&w.goals[1];}

}
function move(w:World,x:number,y:number,r=18){x=Math.max(90,Math.min(W-85,x));y=Math.max(100,Math.min(H-85,y));for(const b of w.walls){if(x>b.x-r&&x<b.x+b.w+r&&y>b.y-r&&y<b.y+b.h+r)return null;}return {x,y};}
function damage(w:World,n:number){const p=w.player;if(p.invul>0)return;p.hp-=n;p.invul=45;burst(w,p.x,p.y,'#ff8eaa');if(p.hp<=0){w.deaths++;p.x=170;p.y=510;p.hp=100;p.invul=120;if(w.stage===6&&w.flags.transaction){resetTransfer(w);tell(w,'Você voltou à base. A transação aberta foi revertida; nenhum crédito se perdeu.','warn');}else{drop(w);tell(w,'Escudo reconstituído na base. Seus sistemas recuperados continuam ativos.','warn');}w.enemies=w.enemies.filter(e=>e.type===3||dist(e,p)>230);}}
export function step(w:World,input:number){if(w.finished)return;w.tick++;const p=w.player;w.messages=w.messages.filter(m=>m.until>w.tick);p.invul=Math.max(0,p.invul-1);p.attack=Math.max(0,p.attack-1);p.dash=Math.max(0,p.dash-1);p.dashTime=Math.max(0,p.dashTime-1);
let dx=(input&INPUT.right?1:0)-(input&INPUT.left?1:0),dy=(input&INPUT.down?1:0)-(input&INPUT.up?1:0);const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;p.faceX=dx;p.faceY=dy;}if(input&INPUT.dash&&p.dash===0){p.dash=65;p.dashTime=9;p.invul=Math.max(p.invul,12);burst(w,p.x,p.y,'#58d9ff',6);}const speed=p.dashTime>0?590:220;let next=move(w,p.x+dx*speed*STEP,p.y);if(next)p.x=next.x;next=move(w,p.x,p.y+dy*speed*STEP);if(next)p.y=next.y;
if(input&INPUT.attack&&p.attack===0){p.attack=10;const target=w.enemies.filter(e=>dist(e,p)<600).sort((a,b)=>dist(a,p)-dist(b,p))[0];let ax=p.faceX,ay=p.faceY;if(target){const d=dist(p,target);ax=(target.x-p.x)/d;ay=(target.y-p.y)/d;}w.shots.push({x:p.x,y:p.y-12,vx:ax*700,vy:ay*700,life:1,hostile:false});w.events++;}
if(input&INPUT.interact){if(!w.interactLock)interact(w);w.interactLock=true;}else w.interactLock=false;if(input&INPUT.drop){if(!w.dropLock)drop(w);w.dropLock=true;}else w.dropLock=false;
const spawnEnabled=!w.goals.every(Boolean);w.spawn--;if(w.spawn<=0&&spawnEnabled&&w.enemies.length<7){enemy(w,1100+rnd(w)*220,150+rnd(w)*700,Math.floor(rnd(w)*3));w.spawn=250;}
for(const e of w.enemies){const d=dist(e,p);e.cool--;const boss=e.type===3;if(d>60){const v=boss?24: e.type===0?80:60;const n=move(w,e.x+(p.x-e.x)/d*v*STEP,e.y+(p.y-e.y)/d*v*STEP,boss?32:20);if(n){e.x=n.x;e.y=n.y;}}if(d<(boss?72:37))damage(w,10);if(e.cool<=0&&d<620){e.cool=boss?48:130;const angle=Math.atan2(p.y-e.y,p.x-e.x);for(let j=0;j<(boss?5:1);j++){const a=angle+(boss?(j-2)*.23:0);w.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*(boss?185:150),vy:Math.sin(a)*(boss?185:150),life:3,hostile:true});}}}
for(const s of w.shots){s.x+=s.vx*STEP;s.y+=s.vy*STEP;s.life-=STEP;if(s.hostile){if(dist(s,p)<22){damage(w,9);s.life=0;}}else for(const e of w.enemies){if(e.hp>0&&dist(s,e)<(e.type===3?50:29)){s.life=0;if(e.type===3&&!w.flags.bossVulnerable){burst(w,e.x,e.y,'#cb8bff',4);if(w.tick%90<11)tell(w,'O escudo depende do relatório e da transferência íntegra. Recupere os dois sistemas.','warn');}else {e.hp--;burst(w,e.x,e.y,'#ffa39d',4);if(e.hp<=0){w.kills++;p.hp=Math.min(100,p.hp+4);if(e.type===3)complete(w,2,'O Fragmentador caiu. A cidade voltou a operar com dados relacionados e transações íntegras.');}}break;}}}w.shots=w.shots.filter(s=>s.life>0&&s.x>0&&s.x<W&&s.y>0&&s.y<H);w.enemies=w.enemies.filter(e=>e.hp>0);
for(const a of w.particles){a.x+=a.vx*STEP;a.y+=a.vy*STEP;a.life-=STEP;}w.particles=w.particles.filter(a=>a.life>0);if(w.goals.every(Boolean)&&!w.flags.exitAnnounced){w.flags.exitAnnounced=true;tell(w,'DISTRITO RECUPERADO! Entre no portal à direita e pressione E.','success');burst(w,1410,500,'#85ffbd',24);}
}
export type Replay=[number,number][];
export function replay(stage:number,seed:number,inputs:Replay){const w=createWorld(stage,seed);let total=0;for(const row of inputs){if(!Array.isArray(row)||row.length!==2||!Number.isInteger(row[0])||row[0]<0||row[0]>255||!Number.isInteger(row[1])||row[1]<1||row[1]>3600)throw Error('Comandos inválidos.');total+=row[1];if(total>216000)throw Error('Registro muito longo. Reinicie este distrito.');for(let i=0;i<row[1];i++)step(w,row[0]);}return w;}
