import assert from 'node:assert/strict';
import {build} from 'esbuild';
await build({entryPoints:['lib/arcade/world.ts'],outfile:'/tmp/nexo-bd1-mechanics.mjs',bundle:true,platform:'node',format:'esm'});
const {createWorld,step,score,replay}=await import('file:///tmp/nexo-bd1-mechanics.mjs');
// Unit scenarios place the player by a station; arcade.mjs uses actual navigation.
function use(w,id){const o=w.objects.find(o=>o.id===id);assert(o,id);w.player.x=o.x;w.player.y=o.y;step(w,0);step(w,32);step(w,0);}
function carry(w,a,b){use(w,a);use(w,b);}
let w=createWorld(0,2);carry(w,'old','core');assert.equal(w.errors,1);assert(!w.goals[0]);assert.equal(w.carry.payload,'old');use(w,'clientA');assert.equal(w.flags.linked,0);
w=createWorld(1,2);use(w,'reservation');assert.equal(w.errors,1);carry(w,'lock','reservation');use(w,'reservation');assert(w.goals[1]);carry(w,'index','concept');assert(!w.goals[2]);use(w,'internal');assert(w.goals[2]);
w=createWorld(2,2);carry(w,'row0','register');carry(w,'row1','register');assert.deepEqual(w.flags.accepted,[11,12]);carry(w,'row2','register');assert.equal(w.errors,1);use(w,'reject');carry(w,'row3','reject');carry(w,'row4','reject');carry(w,'row5','reject');assert(w.goals.every(Boolean));use(w,'course7');assert.equal(w.errors,2);
w=createWorld(3,2);for(const pair of [['person','personPad'],['project','projectPad'],['relation','relationPad'],['attribute','attributePad']])carry(w,...pair);use(w,'bridge');assert.equal(w.flags.links,1);carry(w,'fan','leftFan');use(w,'bridge');assert.equal(w.flags.links,2);carry(w,'fan','rightFan');use(w,'bridge');assert.equal(w.flags.links,3);assert(w.goals.every(Boolean));
w=createWorld(4,2);carry(w,'bundle','splitter');carry(w,'price','itemTable');assert.equal(w.errors,1);assert.equal(w.carry.payload,'price');use(w,'productTable');assert(w.flags.routed.includes('price'));carry(w,'clientFK','clientTable');assert.equal(w.errors,2);use(w,'orderTable');
w=createWorld(5,2);use(w,'toolCREATE');use(w,'forge');use(w,'toolINSERT');for(let i=0;i<4;i++)use(w,'forge');use(w,'toolDELETE');use(w,'forge');assert(w.flags.exists);assert.equal(w.flags.rows.length,0);assert(!w.goals.every(Boolean));use(w,'toolDROP');use(w,'forge');assert(!w.flags.exists);use(w,'toolCREATE');use(w,'forge');use(w,'toolINSERT');for(let i=0;i<4;i++)use(w,'forge');use(w,'where3');use(w,'toolUPDATE');use(w,'forge');assert(w.goals[1]);use(w,'where4');use(w,'toolDELETE');use(w,'forge');assert(w.goals.every(Boolean));assert.equal(w.flags.rows.length,3);
w=createWorld(6,2);carry(w,'inner','joinPad');carry(w,'group','groupPad');carry(w,'where','havingPad');use(w,'report');assert(!w.goals[0]);carry(w,'left','joinPad');use(w,'report');assert(w.flags.reportRows.includes('omitidas'));carry(w,'having','havingPad');use(w,'report');assert(w.goals[0]);use(w,'begin');carry(w,'origin','destination');assert(w.flags.failed);use(w,'commit');assert.equal(w.flags.source,60);assert.equal(w.flags.dest,0);assert(!w.goals[1]);use(w,'begin');carry(w,'origin','destination');use(w,'commit');assert.equal(w.flags.source+w.flags.dest,60);assert(w.flags.bossVulnerable);
assert.throws(()=>replay(0,1,[[1,3601]]));assert.throws(()=>replay(0,1,[[999,1]]));
console.log('PASS: stale records, concurrency, physical independence, PK/FK/domain, N:M links, normalization, DELETE/DROP recovery, JOIN/HAVING, atomic transfer and replay bounds.');
