import { env } from 'cloudflare:workers';
import { chapters,replay,score } from '@/lib/arcade/world';
export const dynamic='force-dynamic';
function db(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
function json(data:any,status=200,cookie?:string){const h:Record<string,string>={'Content-Type':'application/json','Cache-Control':'no-store'};if(cookie)h['Set-Cookie']=cookie;return new Response(JSON.stringify(data),{status,headers:h});}
function sid(req:Request){return req.headers.get('cookie')?.match(/(?:^|;\s*)nexo_bd1_attempt=([a-f0-9]{64})/)?.[1];}
function publicState(row:any){const state=JSON.parse(row.state);return {name:row.name,seed:row.seed,stage:row.stage,state,score:row.score,revision:row.revision,completed:row.completed,receipt:row.id.slice(0,10).toUpperCase()};}
async function current(req:Request){const id=sid(req);return id?await db().prepare('SELECT * FROM attempts WHERE id = ?').bind(id).first<any>():null;}

export async function GET(req:Request){try{const row=await current(req);return json({attempt:row?.mode==='arcade'?publicState(row):null});}catch{return json({error:'Não foi possível recuperar o progresso. Tente novamente.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Origem não permitida.'},403);if(Number(req.headers.get('content-length')||0)>400000)return json({error:'Partida muito longa. Reinicie o distrito.'},413);const raw=await req.text();if(raw.length>400000)return json({error:'Partida muito longa. Reinicie o distrito.'},413);let body:any;try{body=JSON.parse(raw);}catch{return json({error:'Dados inválidos.'},400);}
if(body.action==='start'){const name=String(body.name||'').trim().replace(/\s+/g,' '),email=String(body.email||'').trim().toLowerCase();if(name.length<5||name.length>120||name.split(' ').length<2||!/^\S+@\S+\.\S+$/.test(email)||email.length>200||body.consent!==true)return json({error:'Preencha nome completo, e-mail válido e confirme o uso dos dados.'},400);const id=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join(''),seed=crypto.getRandomValues(new Uint32Array(1))[0]%100000;const state=chapters.map(()=>({best:0,cleared:false,deaths:0,errors:0,kills:0,ticks:0}));const row={id,name,email,seed,stage:0,state:JSON.stringify(state),score:0,revision:0,created:new Date().toISOString(),completed:null};await db().prepare('INSERT INTO attempts (id,name,email,seed,stage,state,score,revision,created,mode) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,name,email,seed,0,row.state,0,0,row.created,'arcade').run();const secure=new URL(req.url).protocol==='https:'?'; Secure':'';return json({attempt:publicState(row)},200,`nexo_bd1_attempt=${id}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure}`);}
const row=await current(req);if(!row||row.mode!=='arcade')return json({error:'A sessão expirou. Inicie uma nova partida.'},401);
// Retrying an already accepted checkpoint is safe, including after a dropped response.
if(body.action==='finish'&&Number.isInteger(body.stage)&&body.stage<row.stage)return json({attempt:publicState(row)});
if(row.completed)return json({attempt:publicState(row)});
if(body.revision!==row.revision||body.stage!==row.stage)return json({error:'Outra aba atualizou esta partida. Recarregue para sincronizar.'},409);
if(body.action!=='finish'||!Array.isArray(body.inputs)||body.inputs.length>24000)return json({error:'Registro da partida inválido.'},400);
let world;try{world=replay(row.stage,row.seed,body.inputs);}catch(e:any){return json({error:e.message},400);}
if(!world.finished)return json({error:'O distrito ainda não foi concluído. Recupere os sistemas e entre no portal.'},400);
const state=JSON.parse(row.state);state[row.stage]={best:score(world),cleared:true,deaths:world.deaths,errors:world.errors,kills:world.kills,ticks:world.tick};row.stage++;if(row.stage===7)row.completed=new Date().toISOString();row.score=state.reduce((n:number,s:any)=>n+s.best,0);row.state=JSON.stringify(state);const update=await db().prepare('UPDATE attempts SET stage=?,state=?,score=?,revision=revision+1,completed=? WHERE id=? AND revision=?').bind(row.stage,row.state,row.score,row.completed,row.id,row.revision).run();if(!update.meta.changes)return json({error:'Outra ação foi salva. Recarregue para sincronizar.'},409);row.revision++;return json({attempt:publicState(row)});
}catch(e){console.error(e);return json({error:'Não conseguimos salvar agora. Mantenha esta tela aberta e tente novamente.'},503);}}
